from __future__ import print_function

"""
 Prompt 72-Errors-and-Exception-Handling - Homework
"""

print("72-Errors-and-Exception-Handling - Homework")

"""

"""

print("\n72-Errors-and-Exception-Handling - Homework\n")
print("- - - - - - - - - - ")


"""
Problem 1
Handle the exception thrown by the code below by using try and except blocks.
"""
try:
    for i in ['a' ,'b', 'c']:
        print(i**2)
except:
    print("Error")
